version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://jegomez:Kuroneco-1@db:5432/school_management
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: school_management
      POSTGRES_USER: jegomez
      POSTGRES_PASSWORD: Kuroneco-1